export const firebaseErrors = {
    "admin-restricted-operation": "Esta operación está restringida a administradores.",
    "argument-error": "",
    "app-not-authorized": "El dominio desde donde intentas acceder no está autorizado.",
    "app-not-installed": "La aplicación debe estar instalada para loguearse.",
    "captcha-check-failed": "Falló la respuesta de validación reCAPTCHA.",
    "code-expired": "El código SMS ha expirado.",
    "cordova-not-ready": "Framework Cordova no está listo.",
    "cors-unsupported": "Este navegador no es soportado por la aplicación.",
    "credential-already-in-use": "Esta credencial ya está en uso para otra sesión",
    "custom-token-mismatch": "El token corresponde a una audiencia diferente.",
    "requires-recent-login": "Esta operación requiere login.",
    "dynamic-link-not-activated": "Activa Dynamic Links en la Firebase Console y acepta los términos y condiciones.",
    "email-change-needs-verification": "Para sesiones multifactor siempre hace falta verificar el email.",
    "email-already-in-use": "La dirección de correo electrónico ya está en uso por otra cuenta.",
    "expired-action-code": "El código de acción ha expirado. ",
    "cancelled-popup-request": "Esta operación se canceló debido a que se abrió otra ventana emergente en conflicto",
    "internal-error": "Ha ocurrido un error interno.",
    "invalid-app-credential": "La solicitud de verificación del teléfono contiene un verificador de aplicación no válido. La respuesta del token reCAPTCHA no es válida o ha caducado.",
    "invalid-app-id": "El identificador de la aplicación móvil no está registrado para el proyecto actual.",
    "invalid-user-token": "La credencial de este usuario no es válida para este proyecto. Esto puede suceder si el token del usuario ha sido alterado o si el usuario no es para el proyecto asociado con esta clave API",
    "invalid-auth-event": "Ha ocurrido un error interno.",
    "invalid-verification-code": "El código de verificación de SMS utilizado para crear la credencial de autenticación del teléfono no es válido. Vuelva a enviar el código de verificación por SMS y asegúrese de usar el código de verificación proporcionado por el usuario.",
    "invalid-continue-uri": "La URL de continuación provista en la solicitud no es válida.",
    "invalid-cordova-configuration": "Se deben instalar los siguientes complementos de Cordova para habilitar el inicio de sesión de OAuth: cordova-plugin-buildinfo, cordova-universal-links-plugin, cordova-plugin-browsertab, cordova-plugin-inappbrowser y cordova -plugin-customurlscheme.",
    "invalid-custom-token": "El formato del token personalizado es incorrecto. Consulte la documentación",
    "invalid-dynamic-link-domain": "El dominio de enlace dinámico proporcionado no está configurado ni autorizado para el proyecto actual.",
    "invalid-email": "La dirección de correo electrónico tiene un formato incorrecto.",
    "invalid-api-key": "Su clave API no es válida, verifique que la haya copiado correctamente",
    "invalid-cert-hash": "El hash del certificado SHA-1 proporcionado no es válido.",
    "invalid-credential": "La credencial de autenticación proporcionada tiene un formato incorrecto o ha caducado.",
    "invalid-message-payload": "La plantilla de correo electrónico correspondiente a esta acción contiene caracteres no válidos en su mensaje. Corríjalo yendo a la sección Plantillas de correo electrónico de autenticación en Firebase Console.",
    "invalid-multi-factor-session": "La solicitud no contiene una prueba válida del primer factor de inicio de sesión exitoso",
    "invalid-oauth-provider": "EmailAuthProvider no es compatible con esta operación. Esta operación solo admite proveedores de OAuth.",
    "invalid-oauth-client-id": "El ID de cliente de OAuth proporcionado no es válido o no coincide con la clave API especificada.",
    "unauthorized-domain": "Este dominio no está autorizado para operaciones de OAuth para su proyecto de Firebase. Edite la lista de dominios autorizados desde la consola de Firebase.",
    "invalid-action-code": "El código de acción no es válido. Esto puede suceder si el código tiene un formato incorrecto, venció o ya se usó",
    "wrong-password": "La contraseña no es válida o el usuario no tiene contraseña.",
    "invalid-persistence-type": "El tipo de persistencia especificado no es válido. Solo puede ser local, de sesión o ninguno.",
    "invalid-phone-number": "El formato del número de teléfono proporcionado es incorrecto. Ingrese el número de teléfono en un formato que pueda analizarse en formato E.164. Los números de teléfono E.164 están escritos en el formato [+] [código de país][número de abonado, incluido el código de área]",
    "invalid-provider-id": "El ID de proveedor especificado no es válido.",
    "invalid-recipient-email": "El correo electrónico correspondiente a esta acción no se pudo enviar porque la dirección de correo electrónico del destinatario proporcionada no es válida",
    "invalid-sender": "La plantilla de correo electrónico correspondiente a esta acción contiene un correo electrónico o un nombre de remitente no válido. Corríjalo yendo a la sección Plantillas de correo electrónico de autenticación en Firebase Console.",
    "invalid-verification-id": "La identificación de verificación utilizada para crear la credencial de autenticación del teléfono no es válida",
    "invalid-tenant-id": "El ID de inquilino de la instancia de autenticación no es válido",
    "multi-factor-info-not-found": "El usuario no tiene un segundo factor que coincida con el identificador proporcionado.",
    "multi-factor-auth-required": "Se requiere prueba de propiedad de un segundo factor para completar el inicio de sesión.",
    "missing-android-pkg-name": "Se debe proporcionar un nombre de paquete de Android si se requiere instalar la aplicación de Android",
    "auth-domain-config-required": "Asegúrese de incluir authDomain cuando llame a firebase.initializeApp(), siguiendo las instrucciones en Firebase console.",
    "missing-app-credential": "A la solicitud de verificación del teléfono le falta una afirmación del verificador de la aplicación. Se debe proporcionar un token de respuesta reCAPTCHA.",
    "missing-verification-code": "La credencial de autenticación del teléfono se creó con un código de verificación de SMS vacío",
    "missing-continue-uri": "Se debe proporcionar una URL de continuación en la solicitud.",
    "missing-iframe-start": "Ha ocurrido un error interno.",
    "missing-ios-bundle-id": "Se debe proporcionar una ID de paquete de iOS si se proporciona una ID de App Store",
    "missing-multi-factor-info": "No se proporciona ningún identificador de segundo factor.",
    "missing-multi-factor-session": "A la solicitud le falta la prueba del inicio de sesión exitoso del primer factor.",
    "missing-or-invalid-nonce": "La solicitud no contiene un nonce válido. Esto puede ocurrir si el hash SHA-256 del nonce sin procesar proporcionado no coincide con el nonce hash en la carga del token de ID",
    "missing-phone-number": "Para enviar códigos de verificación, proporcione un número de teléfono para el destinatario.",
    "missing-verification-id": "La credencial de autenticación del teléfono se creó con una ID de verificación vacía.",
    "app-deleted": "Esta instancia de FirebaseApp ha sido eliminada.",
    "account-exists-with- different-credential": "Ya existe una cuenta con la misma dirección de correo electrónico pero con diferentes credenciales de inicio de sesión. Inicie sesión con un proveedor asociado con esta dirección de correo electrónico.",
    "network-request-failed": "Ocurrió un error de red (como tiempo de espera, conexión interrumpida o host inaccesible).",
    "no-auth-event": "Ha ocurrido un error interno.",
    "no-such-provider": "El usuario no estaba vinculado a una cuenta con el proveedor indicado.",
    "null-user": "Se proporcionó un objeto de usuario nulo como argumento para una operación que requiere un objeto de usuario no nulo.",
    "operation-not-allowed": "El proveedor de inicio de sesión dado está deshabilitado para este proyecto de Firebase. Habilítelo en la consola de Firebase, en la pestaña de método de inicio de sesión de la sección Auth.",
    "operation-not-supported-in-this-environment": 'Esta operación no es compatible con el entorno en el que se ejecuta esta aplicación. "ubicación.protocolo" debe ser http, https o chrome-extension y el almacenamiento web debe estar habilitado.',
    "popup-blocked": "No se pudo establecer una conexión con la ventana emergente. Puede haber sido bloqueada por el navegador.",
    "popup-closed-by-user": "El usuario cerró la ventana emergente antes de finalizar la operación.",
    "provider-already-linked": "El usuario solo puede estar vinculado a una identidad para el proveedor dado.",
    "quota-exceeded": "Se excedió la cuota del proyecto para esta operación.",
    "redirect-cancelled-by-user": "La operación de redirección ha sido cancelada por el usuario antes de finalizar.",
    "redirect-operation-pending": "Ya está pendiente una operación de inicio de sesión de redirección.",
    "rejected-credential": "La solicitud contiene credenciales mal formadas o que no coinciden.",
    "second-factor-already-in-use": "El segundo factor ya está registrado en esta cuenta.",
    "maximum-second-factor-count-exceeded": "Se ha excedido el número máximo permitido de segundos factores en un usuario.",
    "tenant-id-mismatch": "El ID de arrendatario proporcionado no coincide con el ID de arrendatario de la instancia de autenticación",
    "timeout": "Se agotó el tiempo de espera de la operación.",
    "user-token-expired": "La credencial del usuario ya no es válida. El usuario debe iniciar sesión nuevamente",
    "too-many-requests": "Hemos bloqueado todas las solicitudes de este dispositivo debido a actividad inusual. Vuelva a intentarlo más tarde",
    "unauthorized-continue-uri": "El dominio de la URL de continuación no está en la lista blanca. Incluya el dominio en la lista blanca de Firebase console.",
    "unsupported-first-factor": "Inscribir un segundo factor o iniciar sesión con una cuenta multifactor requiere iniciar sesión con un primer factor admitido",
    "unsupported-persistence-type": "El entorno actual no admite el tipo de persistencia especificado.","unsupported-tenant-operation": "Esta operación no se admite en un contexto de múltiples inquilinos",
    "unverified-email": "La operación requiere un correo electrónico verificado.",
    "user-cancelled": "El usuario no otorgó a tu aplicación los permisos que solicitó.",
    "user-not-found": "No hay registro de usuario correspondiente a este identificador. Es posible que el usuario haya sido eliminado.",
    "user-disabled": "La cuenta de usuario ha sido deshabilitada por un administrador.",
    "user-mismatch": "Las credenciales proporcionadas no corresponden al usuario que inició sesión anteriormente.",
    "usuario-cerrado sesión": "",
    "weak-password": "La contraseña debe tener 6 caracteres o más.",
    "web-storage-unsupported": "Este navegador no es compatible o las cookies y los datos de terceros pueden estar deshabilitados",
    "missing-email":"Ingrese un email"
}